# Training on The Pile dataset
parscale:
  parscale_n: 4
  parscale_n_tokens: 48
  parscale_enable_cross_attn: true
  parscale_cross_attn_layers: null

training:
  base_model: "Qwen/Qwen2-1.5B"
  dataset: "EleutherAI/pile"
  output_dir: "./models/parscale-pile"
  max_length: 1024
  per_device_train_batch_size: 4
  gradient_accumulation_steps: 4
  num_train_epochs: 1
  learning_rate: 3e-5
  warmup_steps: 1000
  save_steps: 1000
  logging_steps: 100
  seed: 42