# ParScale with cross-attention on specific layers
parscale:
  parscale_n: 4
  parscale_n_tokens: 48
  parscale_enable_cross_attn: true
  parscale_cross_attn_layers: [0, 4, 8, 12, 16, 20]  # Specific layers only

training:
  base_model: "Qwen/Qwen2-1.5B"
  dataset: "bigcode/the-stack"
  output_dir: "./models/parscale-selective"
  max_length: 2048
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 8
  num_train_epochs: 1
  learning_rate: 5e-5
  warmup_steps: 1000
  save_steps: 1000
  logging_steps: 100
  seed: 42